# Generated by Django 3.1.12 on 2024-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamified_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
